package com.cs407.lab5_milestone.data

import android.content.Context
import androidx.paging.PagingSource
import androidx.room.ColumnInfo
import androidx.room.Dao
import androidx.room.Database
import androidx.room.Delete
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.Insert
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.Transaction
import androidx.room.TypeConverter
import androidx.room.TypeConverters
import androidx.room.Update
import androidx.room.Upsert
import com.cs407.lab5_milestone.NoteAdapter
import com.cs407.lab5_milestone.NoteListFragmentDirections
import com.cs407.lab5_milestone.R
import com.cs407.lab5_milestone.UserState
import com.cs407.lab5_milestone.UserViewModel
import java.util.Date

// Define your own @Entity, @Dao and @Database
@Entity(
    indices = [Index(
        value = ["userName"], unique = true
    )]
)
data class User(
    @PrimaryKey(autoGenerate = true) val userId: Int = 0, //auto generated primary key for user
    val userName: String = "" //the username field, unique due to the index
)

//converter class to handle conversion between custom type Date and SQL-compatible type long
class Converters {
    //converts a timestamp (long) to a date object
    @TypeConverter
    fun fromTimestamp(value: Long): Date {
        return Date(value)
    }

    //converts a Date object to a timestamp (Long)
    @TypeConverter
    fun dateToTimestamp(date: Date): Long {
        return date.time
    }
}

//Define the note entity with a primary key and various fields, including nullable fields
@Entity
data class Note(
    @PrimaryKey(autoGenerate = true) val noteId: Int = 0, //autogenerated primary key for note
    val noteTitle: String, //title of the note
    val noteAbstract: String, //short summary of the note
    //Detailed content of the note (optional might be null)
    @ColumnInfo(typeAffinity = ColumnInfo.TEXT) val noteDetail: String?,
    val notePath: String?, //Path to the note's file(optional)
    val lastEdited: Date //Date of the last edit of the note
)

@Entity(
    primaryKeys = ["userId", "noteId"], // Composite primary key combining userId ănd noteld
    foreignKeys = [ForeignKey(
        entity = User::class, // Foreign key referencing, User
        parentColumns = ["userId"], // Parent column in User entity
        childColumns = ["userId"], // Corresponding child column in this entity
        onDelete = ForeignKey.CASCADE // Cascade delete UserNoteRelation when User is deleted
    ), ForeignKey(
        entity = Note::class, // Foreign key referencing Note
        parentColumns = ["noteId"], // Parent column in Note entity
        childColumns = ["noteId"], // Corresponding child column in this entity
        onDelete = ForeignKey.CASCADE // Cascade delete UserNoteRelation when Note is deleted
    )]
)
data class UserNoteRelation(
    val userId: Int, // Foreign key to User
    val noteId: Int //Foreign key to Note
)

//A summary projection of the Note entity, for displaying limited fields in queries
data class NoteSummary(
    val noteId: Int, //ID of the note
    val noteTitle: String, //Title of the note
    val noteAbstract: String, //Summary of the note
    val lastEdited: Date //Date of the last edit
)

//DAO (data access object) for interacting with the User entity in the database
@Dao
interface UserDao {
    //Query to get a User by their username
    @Query("SELECT * FROM user WHERE userName = :name")
    suspend fun getByName(name: String): User

    //Query to get a User by their userId
    @Query("SELECT * FROM user WHERE userId = :id")
    suspend fun getById(id: Int): User

    //Query to get a list of NoteSummary for a user, ordered by last edited
    @Query(
        """SELECT * FROM User, Note, UserNoteRelation
                WHERE User.userId = :id
                    AND UserNoteRelation.userId = User.userId
                    AND Note.noteId = UserNoteRelation.noteId
                ORDER BY Note.lastEdited DESC"""
    )
    suspend fun getUsersWithNoteListsById(id: Int): List<NoteSummary>

    //Same query but returns a PagingSource for pagination
    @Query(
        """SELECT * FROM User, Note, UserNoteRelation
                WHERE User.userId = :id
                    AND UserNoteRelation.userId = User.userId
                    AND Note.noteId = UserNoteRelation.noteId
                ORDER BY Note.lastEdited DESC"""
    )
    fun getUsersWithNoteListsByIdPaged(id: Int): PagingSource<Int, NoteSummary>

    //insert a new user into the database
    @Insert(entity = User::class)
    suspend fun insert(user: User)
}

//DAO (data access object) for interacting with the User entity in the database
@Dao
interface NoteDao {
    //Query to get a Note by its noteId
    @Query("SELECT * FROM note WHERE noteId = :id")
    suspend fun getById(id: Int): Note

    //Query to get a note's ID by its rowId (SQLite internal ID)
    @Query("SELECT noteId FROM note WHERE rowid = :rowId")
    suspend fun getByRowId(rowId: Long): Int

    //Insert or update a Note(upsert operation)
    @Upsert(entity = Note::class)
    suspend fun upsert(note: Note): Long

    //insert a relation between a user and a note
    @Insert
    suspend fun insertRelation(userAndNote: UserNoteRelation)

    //Insert or update a note and create a relation to the user if it's a new note
    @Transaction
    suspend fun upsertNote(note: Note, userId: Int) {
        val rowId = upsert(note)
        if (note.noteId == 0) { //New note
            val noteId = getByRowId(rowId)
            insertRelation(UserNoteRelation(userId, noteId))
        }
    }

    //Query to count the number of notes a user has
    @Query(
        """SELECT COUNT(*) FROM User, Note, UserNoteRelation
            WHERE User.userId = :userId
                AND UserNoteRelation.userId = User.userId
                AND Note.noteId = UserNoteRelation.noteId"""
    )
    suspend fun userNoteCount(userId: Int): Int
}

//DAO (data access object) for handling deletion of users and their related notes
@Dao
interface DeleteDao {
    //Delete a user by their userId
    @Query("DELETE FROM user WHERE userId = :userId")
    suspend fun deleteUser(userId: Int)

    //Query to get all note IDs related to the user
    @Query(
        """SELECT Note.noteId FROM User, Note, UserNoteRelation
            WHERE User.userId = :userId
                AND UserNoteRelation.userId = User.userId
                AND Note.noteId = UserNoteRelation.noteId"""
    )
    suspend fun getAllNoteIdsByUser(userId: Int): List<Int>

    //delete notes by their ids
    @Query("DELETE FROM note WHERE noteId IN (:notesIds)")
    suspend fun deleteNotes(notesIds: List<Int>)

    //delete note by their note ID
    @Query("DELETE FROM note WHERE noteId = :noteId")
    suspend fun deleteNote(noteId: Int)

    //Transaction to delete a user and all their notes
    @Transaction
    suspend fun delete(userId: Int) {
        deleteNotes(getAllNoteIdsByUser(userId))
        deleteUser(userId)
    }
}

// Database class with all entities and DAOs
@Database(entities = [User::class, Note::class, UserNoteRelation::class], version = 1)
// Database class with all' entities and DAOs
@TypeConverters(Converters::class)
abstract class NoteDatabase : RoomDatabase() {
    // Provide DAOs to access the database
    abstract fun userDao(): UserDao
    abstract fun noteDao(): NoteDao
    abstract fun deleteDao(): DeleteDao

    companion object {
        // Singleton prevents multiple instances of database opening at the
        // same time.
        @Volatile
        private var INSTANCE: NoteDatabase? = null

        //Get or create the database instance
        fun getDatabase(context: Context): NoteDatabase {
            // if the INSTANCE is not null, then return it,
            // if-it is, then create the database
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    NoteDatabase::class.java,
                    context.getString(R.string.note_database), // Database name from resources ). buildO
                ).build()
                INSTANCE = instance
                // return instance
                instance
            }
        }
    }
}